SELECT YEAR, MONTH,
    COUNT(USER_ID) AS PUCHASED_USERS,
    ROUND( COUNT(USER_ID)/ (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021) ,1) AS PUCHASED_RATIO
FROM (
    SELECT
        DISTINCT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
        O.USER_ID AS USER_ID
    FROM USER_INFO AS U
    JOIN ONLINE_SALE AS O
    ON U.USER_ID = O.USER_ID
    WHERE YEAR(JOINED) = 2021 
) AS C
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH