SELECT REST.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS REST
JOIN REST_REVIEW AS REVIEW
ON REST.REST_ID = REVIEW.REST_ID
WHERE ADDRESS LIKE '¼­¿ï%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC